#+TITLE: init.org
#+STARTUP: indent overview

* Prologue
** Lexical Binding
#+begin_src emacs-lisp
  ;;; init.el -*- lexical-binding: t; -*-
#+end_src
** Straight.el
Straight.el is a declarative package manager for Emacs.
#+begin_src emacs-lisp
  (setq straight-use-symlinks t
        straight-disable-autoloads t
        straight-vc-git-default-clone-depth 1)
#+end_src
*** Straight.el Emacs 28 hack
#+begin_src emacs-lisp
  (defvaralias 'comp-deferred-compilation-deny-list 'native-comp-deferred-compilation-deny-list)
#+end_src
*** Bootstrap straight.el
#+begin_src emacs-lisp
  (let ((dest (expand-file-name "straight/repos/straight.el/" user-emacs-directory))
        (repo "https://github.com/raxod502/straight.el.git"))
    (unless (file-directory-p dest)
      (call-process "git" nil nil nil "clone" "--depth" "1" repo dest))
    (require 'straight (expand-file-name "straight.el" dest))
    (with-temp-buffer
      (insert-file-contents (expand-file-name "bootstrap.el" dest))
      (eval-region (search-forward "(require 'straight)")
                   (point-max))))
#+end_src
** GCMH
GCMH is an intelligent garbage collector scheduler for Emacs.
#+begin_src emacs-lisp
  (straight-use-package 'gcmh)
  (require 'gcmh)
  (gcmh-mode +1)
#+end_src
* User interface
** Completion
*** Consult
#+begin_src emacs-lisp
  (straight-use-package 'consult)
  (autoload 'consult-completion-in-region "consult" "Prompt for completion of region in the minibuffer if non-unique.")
  (advice-add 'completion-in-region :override #'consult-completion-in-region)
#+end_src
*** Marginalia
#+begin_src emacs-lisp
  (straight-use-package 'marginalia)
  (require 'marginalia)
  (marginalia-mode +1)
#+end_src
*** Orderless
Smarter sorting in completion buffers.
#+begin_src emacs-lisp
  (straight-use-package 'orderless)
  (require 'orderless)
  (setq completion-styles '(orderless))
#+end_src
*** Vertico
Minimal and compatible completion framework.
#+begin_src emacs-lisp
  (straight-use-package 'vertico)
  (require 'vertico)
  (vertico-mode +1)
#+end_src
** Default font
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(font . "Source Code Pro-12"))
#+end_src
** Disable extra user interface
#+begin_src emacs-lisp
  (setq inhibit-startup-screen t
        use-dialog-box nil)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
#+end_src
** Highlight matching parenthesis
#+begin_src emacs-lisp
  (show-paren-mode +1)
#+end_src
** Line numbers
#+begin_src emacs-lisp
  (setq display-line-numbers-type t)
  (global-display-line-numbers-mode +1)
#+end_src
** Show whitespace
#+begin_src emacs-lisp
  (setq whitespace-style '(face tabs trailing tab-mark))
  (global-whitespace-mode +1)
#+end_src
** Tab bar
Like vim tabs.
#+begin_src emacs-lisp
  (setq tab-bar-close-button nil)
  (setq tab-bar-new-button nil)
  (tab-bar-mode +1)
#+end_src
** Theme
#+begin_src emacs-lisp
  (straight-use-package 'atom-one-dark-theme)
  (require 'atom-one-dark-theme)
  (load-theme 'atom-one-dark t)
#+end_src
** Truncate lines
#+begin_src emacs-lisp
  (setq-default truncate-lines t)
#+end_src
* Editing
** Electric pairs mode
#+begin_src emacs-lisp
  (electric-pair-mode +1)
#+end_src
** Indentation
#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil
                tab-width 4)
  (straight-use-package 'dtrt-indent)
  (require 'dtrt-indent)
  (dtrt-indent-global-mode +1)
#+end_src
** Tab complete
#+begin_src emacs-lisp
  (setq tab-always-indent 'complete)
#+end_src
* Major modes
** Cc
#+begin_src emacs-lisp
  (with-eval-after-load "cc-mode"
    (advice-add 'c-indent-command :override #'indent-for-tab-command))
#+end_src
** Dired
#+begin_src emacs-lisp
  (setq dired-listing-switches "-l -hgvAFX --group-directories-first")
  (require 'dired-x)
#+end_src
** Erc
#+begin_src emacs-lisp
  (with-eval-after-load "erc"
    (setq erc-default-server "irc.libera.chat"
          erc-default-port 6697
          erc-prompt-for-nickserv-password nil
          erc-use-auth-source-for-nickserv-password t
          erc-prompt-for-password nil))
#+end_src
** Magit
#+begin_src emacs-lisp
  (straight-use-package 'magit)
  (autoload 'magit "magit" "An alias for ‘magit-status’ for better discoverability." t)
#+end_src
** Markdown
#+begin_src emacs-lisp
  (straight-use-package 'markdown-mode)
  (autoload 'markdown-mode "markdown-mode" "Major mode for editing Markdown files." t)
  (add-to-list 'auto-mode-alist '("\\.\\(?:md\\|markdown\\|mkd\\|mdown\\|mkdn\\|mdwn\\)\\'" . markdown-mode))
#+end_src
** Zig
#+begin_src emacs-lisp
  (straight-use-package 'zig-mode)
  (setq zig-format-on-save nil)
  (autoload 'zig-mode "zig-mode" "A major mode for the Zig programming language." t)
  (add-to-list 'auto-mode-alist '("\\.zig\\'" . zig-mode))
#+end_src
* Sundry
** Clean file system
#+begin_src emacs-lisp
  (setq auto-save-default nil
        backup-inhibited t
        create-lockfiles nil)
#+end_src
** Don't show compilation warnings
#+begin_src emacs-lisp
  (with-eval-after-load "warnings"
    (add-to-list 'warning-suppress-types '(comp)))
#+end_src
** Eglot
Eglot is a language server protocol (LSP) client for Emacs.
#+begin_src emacs-lisp
  (straight-use-package 'eglot)
  (autoload 'eglot "eglot" "Manage a project with a Language Server Protocol (LSP) server" t)
#+end_src
** Follow symlinks
#+begin_src emacs-lisp
  (setq find-file-visit-truename t
        vc-follow-symlinks t)
#+end_src
