#+TITLE: Faerryn's Emacs Config
#+STARTUP: indent overview

Welcome to my humble parish of the Church of Emacs.
* Prologue
This section contains essential components necessary for the rest of
my config to work.
** Lexical Binding
[[info:elisp#Lexical Binding][Lexical Binding]] encapsulates the scoping of variables to their
context.  This can make bugs easier to catch and improve performance.
#+begin_src emacs-lisp
  ;;; init.el -*- lexical-binding: t; -*-
#+end_src
** Packages
Emacs has as package manager to install useful extensions.
#+begin_src emacs-lisp
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  (defun faerryn/package-ensure (p)
    (add-to-list 'package-selected-packages p)
    (unless (package-installed-p p)
      (package-install p t)))
#+end_src
** Garbage Collector
GCMH is an intelligent garbage collection scheduler for Emacs.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'gcmh)
  (gcmh-mode +1)
#+end_src
* User Interface
Blinging out Emacs since 2021.
** Declutter Widgets
Decluttering Emacs of frivolous things like menus and scroll bars.
#+begin_src emacs-lisp
  (custom-set-variables
   '(inhibit-startup-screen t)
   '(use-dialog-box nil))
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (tooltip-mode -1)
#+end_src
** Line Numbers
Line numbers are crucial to understand where you are in a document.
#+begin_src emacs-lisp
  (custom-set-variables
   '(display-line-numbers-type t))
  (global-display-line-numbers-mode +1)
#+end_src
** Minibuffer Completion
Emacs prompts for input through the minibuffer, which often includes
tab completion and other useful features.
*** Consult
Consult provides a collection of useful functions that make use of minibuffer completion.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'consult)
  (setq completion-in-region-function #'consult-completion-in-region)
#+end_src
*** Marginalia
Marginalia provides extra information in the "margins" during minibuffer completion.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'marginalia)
  (marginalia-mode +1)
#+end_src
*** Vertico
Vertico provices a performant and extensible minibuffer-based completion framework.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'vertico)
  (vertico-mode +1)
#+end_src
** Rainbow
Paint the background of color codes with the color they represent upon
calling `rainbow-mode'.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'rainbow-mode)
#+end_src
** Show Paren
This highlights matching quotes, parentheses, brackets, etc...
#+begin_src emacs-lisp
  (show-paren-mode +1)
#+end_src
** Silent Bell
Loud bells annoy me.
#+begin_src emacs-lisp
  (custom-set-variables
   '(visible-bell t))
#+end_src
** Tab Bar
The tab bar manages different buffers and window configuration in
different tabs.  This feature seems stolen from Vim.
#+begin_src emacs-lisp
  (setq tab-bar-close-button nil
        tab-bar-new-button nil)
  (tab-bar-mode +1)
#+end_src
** Theme
Nice themes are nice!
#+begin_src emacs-lisp
  (faerryn/package-ensure 'modus-themes)
  (load-theme 'modus-vivendi t)
#+end_src
** Truncate Lines
Line wrap is weird and confusing.  Truncated lines are elephants.
#+begin_src emacs-lisp
  (custom-set-variables
   '(truncate-lines t))
#+end_src
** Whitespace
Display normally transparent characters.  Catch the trailing spaces.
#+begin_src emacs-lisp
  (custom-set-variables
   '(whitespace-style '(face tabs trailing tab-mark)))
  (global-whitespace-mode +1)
#+end_src
* Text Editing
Emacs is a text-editor, after all.
** Custom Keys
Key bindings are the bread and butter of Emacs.  It goes to reason
that you can define your own!
#+begin_src emacs-lisp
  (define-key (current-global-map) (kbd "C-c x") #'fixup-whitespace)
#+end_src
** Electric Pairs
Automagically close quotes, parentheses, brackets, etc...
#+begin_src emacs-lisp
  (electric-pair-mode +1)
#+end_src
** Indentation
Indent with spaces.
#+begin_src emacs-lisp
  (custom-set-variables
   '(indent-tabs-mode nil))
#+end_src
** LSP Client
[[https://microsoft.github.io/language-server-protocol][Language server protocol]] is a protocol invovling a server generating
intelligent code assistance for an abitrary editor that supports the
protocol.  It brings IDE-grade completion and linting to any
LSP-capable editor.

Eglot is a LSP client written in Elisp, bringing the power of an IDE
to Emacs.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'eglot)
  (with-eval-after-load "eglot"
    (define-key eglot-mode-map (kbd "C-c a") #'eglot-code-actions)
    (define-key eglot-mode-map (kbd "C-c r") #'eglot-rename)
    (define-key eglot-mode-map (kbd "C-c f") #'eglot-format))
#+end_src
** Tab Completion
Bring the tab completion to Emacs!
#+begin_src emacs-lisp
  (custom-set-variables
   '(tab-always-indent 'complete))
#+end_src
* Major Modes
Major modes represent filetypes in Emacs.
** Dired
Dired is the file browser in Emacs.  Dired-x contains extra features.
#+begin_src emacs-lisp
  (custom-set-variables
   '(dired-x-hands-off-my-keys nil))
  (require 'dired-x)
  (add-hook 'dired-mode-hook #'dired-omit-mode)
#+end_src
** Org
Emacs' Org mode has superpowers.
#+begin_src emacs-lisp
  (custom-set-variables
   '(org-catch-invisible-edits 'smart))
  (require 'org-table)
  (add-hook 'lisp-interaction-mode-hook #'orgtbl-mode)
#+end_src
** Tex
#+begin_src emacs-lisp
  (faerryn/package-ensure 'auctex)
#+end_src
* Window Manager
EXWM is a window manager written in Elisp.  Lots of hacks are used to
customize the behavior of EXWM.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'exwm)
#+end_src

This defines key behaviors for EXWM.
#+begin_src emacs-lisp
  (with-eval-after-load "exwm"
    (define-key exwm-mode-map (kbd "C-q") #'exwm-input-send-next-key))
  (custom-set-variables
   '(exwm-input-prefix-keys (mapcar #'kbd '("C-c" "C-g" "C-h" "C-u" "C-x" "M-!" "M-&" "M-:" "M-x"))))
#+end_src

This sets the modeline up for a full environment.
#+begin_src emacs-lisp
  (add-hook 'exwm-init-hook #'display-time-mode)
  (add-hook 'exwm-init-hook #'display-battery-mode)
#+end_src

This gets rid of EXWM's buffer-predicate settings.
#+begin_src emacs-lisp
  (defun faerryn/exwm-workspace-init-fix (oldfun)
    (advice-add #'modify-all-frames-parameters :override #'ignore)
    (funcall oldfun)
    (advice-remove #'modify-all-frames-parameters #'ignore))
  (advice-add #'exwm-workspace--init :around #'faerryn/exwm-workspace-init-fix)
  (defun faerryn/mfp-ignore-bp (oldfun frame alist)
    (funcall oldfun frame (assoc-delete-all 'buffer-predicate alist)))
  (defun faerryn/exwm-workspace-exit-fix (oldfun)
    (advice-add #'modify-frame-parameters :around #'faerryn/mfp-ignore-bp)
    (funcall oldfun)
    (advice-remove #'modify-frame-parameters #'faerryn/mfp-ignore-bp))
  (advice-add #'exwm-workspace--exit :around #'faerryn/exwm-workspace-exit-fix)
#+end_src

This names exwm buffers according to the X11 window class.
#+begin_src emacs-lisp
  (defun faerryn/exwm-rename-buffer ()
    (rename-buffer (concat "*EXWM " exwm-class-name "*") t))
  (add-hook 'exwm-update-class-hook #'faerryn/exwm-rename-buffer)
  (add-hook 'exwm-update-title-hook #'faerryn/exwm-rename-buffer)
#+end_src
* Sundry
Miscellaneous items that don't fall into a broader category.
** Async Shell Command
Configure the behavior of [[help:async-shell-command]]
#+begin_src emacs-lisp
  (custom-set-variables
   '(async-shell-command-buffer 'rename-buffer))
  (add-to-list 'display-buffer-alist
               '("\\`\\*Async Shell Command\\*"
                 (display-buffer-no-window)))
#+end_src
** Declutter File System
Disable autosaves, backups, and lockfiles for file system sanity.
#+begin_src emacs-lisp
  (custom-set-variables
   '(auto-save-default nil)
   '(make-backup-files nil)
   '(create-lockfiles nil))
#+end_src
** Highlight VC Diff
Diff-hl shows uncommitted changes in the buffer.
#+begin_src emacs-lisp
  (faerryn/package-ensure 'diff-hl)
  (global-diff-hl-mode +1)
  (add-hook 'diff-hl-mode-hook #'diff-hl-flydiff-mode)
  (add-hook 'dired-mode-hook #'diff-hl-dired-mode)
#+end_src
** EMMS
#+begin_src emacs-lisp
  (faerryn/package-ensure 'emms)
  (custom-set-variables
   '(emms-source-file-default-directory "~/Music/"))
  (with-eval-after-load "emms"
    (emms-all)
    (emms-default-players))
#+end_src
** Follow Symlinks
For symlinks are good.
#+begin_src emacs-lisp
  (custom-set-variables
   '(find-file-visit-truename t)
   '(vc-follow-symlinks t))
#+end_src
** Tramp
Tramp is how Emacs can access remote files as if they were local.

Let Tramp inherit the remote's PATH environmental variable.
#+begin_src emacs-lisp
  (with-eval-after-load "tramp"
    (add-to-list 'tramp-remote-path 'tramp-own-remote-path))
#+end_src
