#+TITLE: init.org
#+STARTUP: indent overview

* Prologue
** Lexical Binding
#+begin_src emacs-lisp
  ;;; init.el -*- lexical-binding: t; -*-
#+end_src
** straight.el
straight.el is a declarative package manager for Emacs.
#+begin_src emacs-lisp
  (setq straight-use-symlinks t
        straight-disable-autoloads t
        straight-vc-git-default-clone-depth 1)
#+end_src
*** straight.el hack
#+begin_src emacs-lisp
  (defvaralias 'comp-deferred-compilation-deny-list
    'native-comp-deferred-compilation-deny-list)
#+end_src
*** Bootstrap straight.el
#+begin_src emacs-lisp
  (let ((dest (expand-file-name "straight/repos/straight.el/" user-emacs-directory))
        (repo "https://github.com/raxod502/straight.el.git"))
    (unless (file-directory-p dest)
      (call-process "git" nil nil nil "clone" "--depth" "1" repo dest))
    (require 'straight (expand-file-name "straight.el" dest))
    (with-temp-buffer
      (insert-file-contents (expand-file-name "bootstrap.el" dest))
      (eval-region (search-forward "(require 'straight)")
                   (point-max))))
#+end_src
*** Clean up straight.el error log
#+begin_src emacs-lisp
  (add-hook 'kill-emacs-hook
            (lambda ()
              (when (zerop (file-attribute-size
                            (file-attributes straight--process-stderr)))
                (delete-file straight--process-stderr))))
#+end_src
** GCMH
GCMH is an intelligent garbage collector scheduler for Emacs.
#+begin_src emacs-lisp
  (straight-use-package 'gcmh)
  (require 'gcmh)
  (gcmh-mode +1)
#+end_src
* User Interface
** Completion
*** vertico
Minimal and compatible completion framework.
#+begin_src emacs-lisp
  (straight-use-package 'vertico)
  (require 'vertico)
  (vertico-mode +1)
#+end_src
*** consult
#+begin_src emacs-lisp
  (straight-use-package 'consult)
  (autoload
    'consult-completion-in-region "consult"
    "Prompt for completion of region in the minibuffer if non-unique.")
  (advice-add 'completion-in-region :override #'consult-completion-in-region)
#+end_src
*** marginalia
Marginal information in completion buffers.
#+begin_src emacs-lisp
  (straight-use-package 'marginalia)
  (require 'marginalia)
  (marginalia-mode +1)
#+end_src
*** orderless
Smarter sorting in completion buffers.
#+begin_src emacs-lisp
  (straight-use-package 'orderless)
  (require 'orderless)
  (setq completion-styles '(orderless))
#+end_src
**** selectrum + orderless hack
#+begin_src emacs-lisp
  (setq selectrum-refine-candidates-function #'orderless-filter
        selectrum-highlight-candidates-function #'orderless-highlight-matches)
#+end_src
** Dark theme
#+begin_src emacs-lisp
  (straight-use-package 'doom-themes)
  (require 'doom-themes)
  (load-theme 'doom-one t)
#+end_src
** Default font
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist
               '(font . "monospace-12"))
#+end_src
** Disable extra user interface
#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
  (setq use-dialog-box nil)
  (menu-bar-mode -1)
  (when (featurep 'scroll-bar) (scroll-bar-mode -1))
  (tool-bar-mode -1)
  (add-hook 'window-setup-hook (lambda () (tooltip-mode -1)))
#+end_src
** Highlight matching parenthesis
#+begin_src emacs-lisp
  (show-paren-mode +1)
#+end_src
** Line numbers
#+begin_src emacs-lisp
  (setq display-line-numbers-type t)
  (global-display-line-numbers-mode +1)
#+end_src
** Show key chords
#+begin_src emacs-lisp
  (straight-use-package 'which-key)
  (require 'which-key)
  (which-key-mode +1)
#+end_src
** Show whitespace
#+begin_src emacs-lisp
  (setq whitespace-style '(face tabs trailing tab-mark))
  (global-whitespace-mode +1)
#+end_src
** Tab bar
Like vim tabs.
#+begin_src emacs-lisp
  (setq tab-bar-close-button nil)
  (setq tab-bar-new-button nil)
  (tab-bar-mode +1)
#+end_src
** Wrap lines
#+begin_src emacs-lisp
  (global-visual-line-mode +1)
#+end_src
* Editing
** Electric pairs mode
#+begin_src emacs-lisp
  (electric-pair-mode +1)
#+end_src
** Indentation
#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil
                tab-width 4)
  (straight-use-package 'dtrt-indent)
  (require 'dtrt-indent)
  (dtrt-indent-global-mode +1)
#+end_src
** Tab complete
#+begin_src emacs-lisp
  (setq tab-always-indent 'complete)
#+end_src
** Evil mode
Vim emulation for Emacs.
#+begin_src emacs-lisp
  (straight-use-package 'evil)
  (setq evil-want-Y-yank-to-eol t
        evil-want-keybinding nil
        evil-undo-system 'undo-redo)
  (require 'evil)
  (evil-mode +1)
#+end_src
*** Evil collection
Vim emulation everywhere.
#+begin_src emacs-lisp
  (straight-use-package 'evil-collection)
  (setq evil-collection-want-unimpaired-p nil)
  (require 'evil-collection)
  (evil-collection-init)
#+end_src
* Major modes
** C/C++
#+begin_src emacs-lisp
  (with-eval-after-load "cc-mode"
    (advice-add 'c-indent-command :override #'indent-for-tab-command))
#+end_src
** Dired
#+begin_src emacs-lisp
  (setq dired-listing-switches "-l -hgvAFX --group-directories-first")
#+end_src
* Sundry
** Clean file system
#+begin_src emacs-lisp
  (setq auto-save-default nil
        backup-inhibited t
        create-lockfiles nil)
#+end_src
** Disable saving passwords
#+begin_src emacs-lisp
  (setq auth-source-save-behavior nil)
#+end_src
** Eglot
Eglot is a language server protocol (LSP) client for Emacs.
#+begin_src emacs-lisp
  (straight-use-package 'eglot)
  (autoload
    'eglot "eglot"
    "Manage a project with a Language Server Protocol (LSP) server" t)
  (with-eval-after-load "eglot"
    (add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))
    (add-to-list 'eglot-server-programs '(rust-mode "rust-analyzer")))
#+end_src
** Follow symlinks
#+begin_src emacs-lisp
  (setq find-file-visit-truename t)
#+end_src
