#! /bin/sh

set -euf

# bspwm specific settings

pgrep -x sxhkd || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# general wm settings

WALLPAPER="${XDG_CONFIG_HOME}"/wallpaper

pgrep -x picom || picom &
pgrep -x redshift || redshift &

echo "${WALLPAPER}" | entr -n hsetroot -cover "${WALLPAPER}" &
