#! /bin/sh

set -euf

# bspwm specific settings

pgrep -x sxhkd || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         1
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focused_border_color '#fabd2f'

# general wm settings
xsetroot -cursor_name left_ptr

XRESOURCES="${XDG_CONFIG_HOME}"/Xresources
[ -f "${XRESOURCES}" ] && xrdb -merge "${XRESOURCES}"

pgrep -x picom || picom &
pgrep -x redshift || redshift &

WALLRC="${XDG_CONFIG_HOME}"/wallrc
[ -f "${WALLRC}" ] || cp "${WALLRC}.def" "${WALLRC}"
echo "${WALLRC}" | entr -n "${WALLRC}" &
