#!/bin/sh

set -euf

# bspwm specific settings

pgrep -x sxhkd || sxhkd "${XDG_CONFIG_HOME}/bspwm/sxhkdrc" &

bspc monitor -d 1 2 3 4

bspc config border_width         1
bspc config window_gap           32

bspc config split_ratio          0.50

bspc config focused_border_color '#fabd2f'

# startup jobs

xsetroot -cursor_name left_ptr

XRESOURCES="${XDG_CONFIG_HOME}"/Xresources
[ -f "${XRESOURCES}" ] && xrdb -merge "${XRESOURCES}"

pgrep -x picom || picom &
pgrep -x pulseaudio || pulseaudio --exit-idle-time -1 &
pgrep -x redshift || redshift &

WALLRC="${XDG_CONFIG_HOME}"/wallrc
[ -f "${WALLRC}" ] && "${WALLRC}"
