set nocompatible

syntax on
filetype plugin indent on

if !has("nvim") && exists("+viminfo")
    set viminfofile=~/.vim/viminfo
endif

set hidden

set tabstop=4
set shiftwidth=4
set expandtab

set undofile

set title

set showtabline=2

set number
set relativenumber

set signcolumn=yes

set splitbelow
set splitright

set linebreak
set wrap

set list
let &listchars = "tab:> ,trail:-,nbsp:+"

set nrformats=alpha,octal,hex,bin

set completeopt=menuone,noinsert

set incsearch
set hlsearch

if exists('+X11')
    set clipboard=unnamedplus
endif

set mouse=ar
noremap <ScrollWheelUp> <C-Y>
noremap <S-ScrollWheelUp> <C-U>
noremap <ScrollWheelDown> <C-E>
noremap <S-ScrollWheelDown> <C-D>

set lazyredraw

set background=dark
if getenv("COLORTERM") == "truecolor"
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set t_Co=256
    set termguicolors
endif

if executable("rg")
    let &grepprg = "rg --hidden --vimgrep"
    let &grepformat = "%f:%l:%c:%m"
endif

noremap Y y$

let g:netrw_banner    = 0
let g:netrw_hide      = 1
let g:netrw_keepdir   = 0
let g:netrw_list_hide = "^\\.\\.\\?/$"
let g:netrw_winsize   = 25

command! Shell  terminal ++curwin
command! Hshell terminal
command! Lshell topleft vertical terminal
command! Sshell terminal
command! Vshell vertical terminal
command! Tshell tab terminal
