#+TITLE: init.org
#+AUTHOR: Jiang Meng Liao (Faerryn)
#+STARTUP: overview

* Vanilla
Configure the basic Emacs settings.
** Async Shell Command
#+begin_src emacs-lisp
  (setq async-shell-command-buffer 'new-buffer)
  (add-to-list 'display-buffer-alist
                '("\\*Async Shell Command\\*.*" display-buffer-no-window nil))
#+end_src
** Disable Auto Save, Lockfiles, Backup
#+begin_src emacs-lisp
  (setq auto-save-default nil
        auto-save-list-file-prefix nil
        create-lockfiles nil
        make-backup-files nil)
#+end_src
** Disable Dialog Box, Tooltip
#+begin_src emacs-lisp
  (setq use-dialog-box nil)
  (tooltip-mode -1)
#+end_src
** Indentation
#+begin_src emacs-lisp
  (setq-default tab-width 2)
#+end_src
** Inhibit Startup Screen
#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
#+end_src
** Mouse Wheel
#+begin_src emacs-lisp
  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1) ((meta)) ((control) . text-scale))
        mouse-wheel-progressive-speed nil)
#+end_src
** Symlinks
Follow symlinks.
#+begin_src emacs-lisp
  (setq find-file-visit-truename t)
#+end_src
** User Emacs Directory
#+begin_src emacs-lisp
  (setq user-emacs-directory
        (expand-file-name "emacs/" (getenv "XDG_DATA_HOME")))
#+end_src
** Truncate Lines
#+begin_src emacs-lisp
  (setq-default truncate-lines t)
#+end_src
* Bootstrap
Bootstrap packages needed for package management.
** straight.el
straight.el is a package manager for emacs that is functional -- that is, packages are only loaded if they are asked for.
Compared to package.el, where any package ever installed is loaded, this makes reverting to a previous configuration must easier.
#+begin_src emacs-lisp
  (setq straight-use-package-by-default t)
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src
** use-package
use-package is a configuration management tool that can defer loading of packages until later. This can improve startup time.
#+begin_src emacs-lisp
  (straight-use-package 'use-package)
  (setq use-package-hook-name-suffix nil)
  (require 'use-package)
#+end_src
** general.el
general.el is a keybinding management tool that integrates well with Evil and use-package.
#+begin_src emacs-lisp
  (use-package general)
#+end_src
* Packages
Configure packages for Emacs glory.
** Dired X
Dired X (Dired Extra) provides extra functionality to Dired, the Emacs file manager.
#+begin_src emacs-lisp
  (use-package dired-x
    :straight nil
    :hook (dired-mode-hook . dired-omit-mode))
#+end_src
** Display Line Numbers
Show relative line numbers on the left gutter.
#+begin_src emacs-lisp
  (use-package display-line-numbers
    :straight nil
    :hook (emacs-startup-hook . global-display-line-numbers-mode)
    :init (setq display-line-numbers-type 'relative))
#+end_src
** Doom Themes
Doom has the best themes, and the best gruvbox!
#+begin_src emacs-lisp
  (use-package doom-themes
    :hook (emacs-startup-hook . (lambda () (load-theme 'doom-gruvbox t))))
#+end_src
** Evil
Evil is a vim emulation layer in emacs.
*** Evil
The emulation package proper, which provides the text editing powers of vim to Emacs.
#+begin_src emacs-lisp
  (use-package evil
    :hook (emacs-startup-hook . evil-mode)
    :init (setq evil-want-integration t
                evil-want-keybinding nil
                evil-want-Y-yank-to-eol t)
    :config
    (require 'undo-fu)
    (require 'undohist)
    (evil-collection-init))
#+end_src
*** Evil Collection
Evil Collection is a collection of vim-style keybindings for various Emacs major modes.
#+begin_src emacs-lisp
  (use-package evil-collection
    :commands evil-collection-init)
#+end_src
*** Undo
**** Undo Fu
Undo Fu for evil mode redo.
#+begin_src emacs-lisp
  (use-package undo-fu
    :defer t
    :init (setq evil-undo-system 'undo-fu))
#+end_src
**** undohist
#+begin_src emacs-lisp
  (use-package undohist
    :defer t
    :init (setq undohist-ignored-files '("\.git/COMMIT_EDITMSG$"))
    :config (undohist-initialize))
#+end_src
** EWW
EWW (Emacs Web Wowser) is good for browsing good ol' static sites.
#+begin_src emacs-lisp
  (use-package eww
    :straight nil
    :init (setq eww-download-directory "~/www/"))
#+end_src
** EXWM
#+begin_src emacs-lisp
  (use-package exwm
    :commands exwm-enable
    :config
    (add-hook 'exwm-init-hook
              (lambda () (make-process :name "sxhkd" :command '("sxhkd") :noquery t)))
    (add-hook 'exwm-update-class-hook (lambda () (rename-buffer exwm-class-name t))))	
#+end_src
** Filetypes
#+begin_src emacs-lisp
  (use-package lua-mode
    :mode "\\.lua\\'")
  (use-package markdown-mode
    :mode "\\.md\\'")
  (use-package zig-mode
    :mode "\\.zig\\'")
#+end_src
** GCMH
GCMH (Garbage Collection Magic Hack) provides a smarter garbage collector that delegates garbage collection to times when Emacs is idle.
#+begin_src emacs-lisp
  (use-package gcmh
    :hook (emacs-startup-hook . gcmh-mode))
#+end_src
** Magit
Magit is the best Git client.
#+begin_src emacs-lisp
  (use-package magit
    :general ("C-c g" 'magit-status)
    :init (setq magit-define-global-key-bindings nil))
#+end_src
** Org
Org is a versatile and powerful plain-text format for Emacs.
#+begin_src emacs-lisp
  (use-package org
    :hook (org-mode-hook . org-indent-mode))
#+end_src
** which-key
#+begin_src emacs-lisp
  (use-package which-key
    :hook (emacs-startup-hook . which-key-mode))
#+end_src
