#+TITLE: init.org
#+STARTUP: overview

* Core
Configure the basic Emacs settings.
** Async Shell Command
Hide async-shell-command buffer.
#+begin_src emacs-lisp
  (setq async-shell-command-buffer 'new-buffer)
  (add-to-list 'display-buffer-alist
               '("^\\*Async Shell Command\\*" . display-buffer-window))
#+end_src
** Display Line Numbers
Show relative line numbers on the left gutter.
#+begin_src emacs-lisp
  (setq display-line-numbers-type 'relative)
  (global-display-line-numbers-mode +1)
#+end_src
** Font
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist
               '(font . "monospace-12"))
#+end_src
** Key Chord Delay
#+begin_src emacs-lisp
  (setq key-chord-two-keys-delay 0.05
        key-chord-one-keys-delay 0.1)
#+end_src
** Mode Line
#+begin_src emacs-lisp
  (display-time-mode +1)
  (display-battery-mode +1)
#+end_src
** Symlinks
Follow symlinks.
#+begin_src emacs-lisp
  (setq find-file-visit-truename t)
#+end_src
* Bootstrap
Bootstrap packages needed for package management.
** straight.el
straight.el is a package manager for emacs that is functional -- that is, packages are only loaded if they are asked for.
Compared to package.el, where any package ever installed is loaded, this makes reverting to a previous configuration must easier.
#+begin_src emacs-lisp
  (setq straight-use-package-by-default t)
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src
** use-package
use-package is a configuration management tool that can defer loading of packages until later. This can improve startup time.
#+begin_src emacs-lisp
  (straight-use-package 'use-package)
  (setq use-package-hook-name-suffix nil)
  (require 'use-package)
#+end_src
** general.el
general.el is a keybinding management tool that integrates well with Evil and use-package.
#+begin_src emacs-lisp
  (use-package general)
#+end_src
* Packages
Configure packages for Emacs glory.
** Dired
Dired is the standard Emacs file manager.
#+begin_src emacs-lisp
  (require 'dired-x)
  (add-hook 'dired-mode-hook
            (lambda () (dired-omit-mode +1)))
  (setq dired-guess-shell-alist-user
        '(("\\.ogg\\'" "mpv")
          ("\\.swf\\'" "ruffle")))
#+end_src
** Evil
Evil is a vim emulation layer in emacs.
*** Evil
The emulation package proper, which provides the text editing powers of vim to Emacs.
#+begin_src emacs-lisp
  (use-package evil
    :hook (emacs-startup-hook . evil-mode)
    :init
    (setq evil-want-integration t
          evil-want-keybinding nil
          evil-want-Y-yank-to-eol t))
#+end_src
*** Evil Collection
Evil Collection is a collection of vim-style keybindings for various Emacs major modes.
#+begin_src emacs-lisp
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src
** EWW
#+begin_src emacs-lisp
  (setq eww-download-directory "~/www/")
#+end_src
** EXWM
EXWM (Emacs X Window Manager) is a window manager for X11 written in Emacs Lisp.
*** EXWM
The window manager proper, which manages X11 windows as Emacs buffers.
#+begin_src emacs-lisp
  (use-package exwm
    :commands exwm-enable
    :config
    (make-process :name "sxhkd" :command '("sxhkd") :noquery t)
    (make-process :name "picom" :command '("picom") :noquery t)
    (make-process :name "redshift" :command '("redshift") :noquery t)

    (add-to-list 'initial-frame-alist
                 '(fullscreen . fullboth))

    (add-hook 'exwm-update-class-hook
              (lambda () (exwm-workspace-rename-buffer exwm-class-name))))
#+end_src
*** Startup Flag
Provide a --exwm flag to request for EXWM.
#+begin_src emacs-lisp
  (add-to-list 'command-switch-alist
               '("--exwm" . (lambda (switch-string) (exwm-enable))))
#+end_src
** GCMH
GCMH (Garbage Collection Magic Hack) provides a smarter garbage collector that delegates garbage collection to times when Emacs is idle.
#+begin_src emacs-lisp
  (use-package gcmh
    :disabled t
    :hook (emacs-startup-hook . gcmh-mode))
#+end_src
** Gruvbox
Gruvbox is the best theme.
#+begin_src emacs-lisp
  (use-package gruvbox-theme
    :config
    (load-theme 'gruvbox t))
#+end_src
** Ivy
*** Ivy
#+begin_src emacs-lisp
  (use-package ivy
    :config
    (ivy-mode +1))
#+end_src
*** Counsel
#+begin_src emacs-lisp
  (use-package counsel
    :hook (emacs-startup-hook . counsel-mode))
#+end_src
*** Swiper
#+begin_src emacs-lisp
  (use-package swiper
    :disabled t
    :general ("C-s" 'swiper-isearch))
#+end_src
** Magit
Magit is the best Git client.
#+begin_src emacs-lisp
  (use-package magit
    :general
    ("C-x g" 'magit-status)
    :init
    (setq magit-define-global-key-bindings nil))
#+end_src
** Org
Org is a versatile and powerful plain-text format for Emacs.
#+begin_src emacs-lisp
  (require 'org)
  (add-hook 'org-mode-hook 'org-indent-mode)
#+end_src

** Undo Fu
Undo Fu for evil mode.
#+begin_src emacs-lisp
  (use-package undo-fu
    :config
    (setq evil-undo-system 'undo-fu))
#+end_src
